version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
    container_name: jaeger
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    ports:
      - "3000:3000"
